import { ArrowDown, ArrowUpRight, ArrowUp, Download, Code2, Sparkles, Linkedin, GraduationCap, Braces, Workflow } from 'lucide-react';
import { Header } from '@/components/header';
import { Effects } from '@/components/effects';
import { ProjectShowcase } from '@/components/project-showcase';
import { Toolkit } from '@/components/toolkit';
import { profile, projects } from '@/lib/content';
import { siteUrl } from '@/lib/site';
import { projectArtwork } from '@/lib/project-art';

const statement = 'I like making complex things feel simple. Especially when there’s a little intelligence behind them.';

export default function Home() {
  const schema = {'@context':'https://schema.org','@graph':[
    {'@type':'Person','@id':`${siteUrl || ''}/#priyansh`,name:profile.name,jobTitle:profile.role,description:profile.description,email:`mailto:${profile.email}`,url:siteUrl||undefined,sameAs:[profile.linkedin],worksFor:{'@type':'Organization',name:'Bitontree'},alumniOf:{'@type':'CollegeOrUniversity',name:'Dharmsinh Desai University'},knowsAbout:['Full-stack development','React','Next.js','Node.js','NestJS','Redis','PostgreSQL','MongoDB','Applied AI','LLM systems','RAG','Python','TypeScript','LangGraph','FastAPI']},
    {'@type':'ProfilePage','@id':`${siteUrl||''}/#profile`,url:siteUrl||undefined,name:`${profile.name} — ${profile.role}`,mainEntity:{'@id':`${siteUrl||''}/#priyansh`}},
    ...projects.map(project=>({'@type':'CreativeWork',name:project.name,description:project.description,about:project.category,image:siteUrl&&projectArtwork[project.id]?`${siteUrl}/projects/${project.id}-1280.webp`:undefined,contributor:{'@id':`${siteUrl||''}/#priyansh`},url:siteUrl?`${siteUrl}/projects/${project.id}/`:undefined}))
  ]};
  return <>
    <link rel="preload" as="image" href="/developer-sprites.webp"/>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/>
    <a className="skip-link" href="#main">Skip to content</a><Effects/><Header/>
    <main id="main">
      <section className="hero container" aria-labelledby="hero-title">
        <div className="hero-copy"><div className="eyebrow"><span className="tiny-line"/> FULL-STACK &amp; APPLIED AI ENGINEER</div><h1 id="hero-title">Human ideas.<br/><span className="serif">Intelligent</span><br/>execution<span className="accent">.</span></h1><p className="hero-intro">Hey, I’m <strong>Priyansh Dobariya.</strong><br/>I build complete web products and intelligent AI systems.<br className="desktop-break"/> From the interface to the API. From idea to production.</p><div className="hero-actions"><a className="button button-primary" href="#work">Explore my work <ArrowDown size={17}/></a><a className="text-link" href="/Priyansh_Resume.pdf" download>Download CV <Download size={17}/></a></div></div>
        <div className="hero-stage"><div className="celestial" aria-hidden="true"><span className="sun-disc"/></div><div className="scene-stars" aria-hidden="true">✧ <span>✦</span> · <b>✧</b></div><div className="code-card floating" aria-hidden="true"><span><Code2 size={16}/> BUILT WITH INTENT</span><code><b>while</b> (curious) {'{'}<br/>&nbsp; learn();<br/>&nbsp; build();<br/>&nbsp; improve();<br/>{'}'}</code></div><div className="character-space"><div className="character-sprite" role="img" aria-label="Animated developer character working on a laptop"/></div><div className="floating-tag" aria-hidden="true"><Braces size={18}/><span>let’s build something.</span></div><div className="scene-caption"><Sparkles size={16}/><span>A little curiosity. A lot of building.</span></div><span className="scene-coordinate">IDEA → INTELLIGENCE → IMPACT</span></div>
        <div className="hero-bottom"><span>Based in India · Building for everywhere</span><a href="#work">SCROLL TO EXPLORE <ArrowDown size={14}/></a><span>CRAFTED WITH CURIOSITY ↗</span></div>
      </section>
      <div className="ticker" aria-label="Specialties: full-stack development, React and Next.js, backend systems, and applied AI"><div className="ticker-track" aria-hidden="true">{[0,1].map(n=><div className="ticker-set" key={n}><span>FULL-STACK DEVELOPMENT</span><span className="ticker-star">✳</span><span>REACT &amp; NEXT.JS</span><span className="ticker-star">✳</span><span>APPLIED AI</span><span className="ticker-star">✳</span><span>BACKEND SYSTEMS</span><span className="ticker-star">✳</span></div>)}</div></div>
      <section id="work" className="section container" aria-labelledby="work-title"><div className="section-heading" data-reveal="wipe"><div><div className="eyebrow">01 / SELECTED WORK</div><h2 id="work-title">Ideas, put to <span className="serif">work.</span></h2></div><p className="section-lede">Real problems. Thoughtful systems.<br/>A few things I’ve helped bring to life.</p></div><ProjectShowcase/><div className="work-note" data-reveal><span>Always exploring. Always building.</span><a className="text-link" href="#contact">Have something in mind? <ArrowUpRight size={16}/></a></div></section>
      <section id="about" className="about-section" aria-labelledby="about-title"><div className="container about-grid"><div className="about-label"><div className="eyebrow">02 / THE PERSON BEHIND THE CODE</div><div className="about-emblem" aria-hidden="true">✳</div><span>CURIOUS BY DEFAULT.</span></div><div className="about-content"><h2 className="about-statement" id="about-title">{statement.split(' ').map((word,i)=><span className={`about-word ${i>12?'serif':''}`} key={i}>{word} </span>)}</h2><div className="about-paragraphs" data-reveal><p>I’m Priyansh, an Applied AI Engineer at Bitontree and a full-stack developer. I build React and Next.js interfaces, Node.js and NestJS backends, and the APIs, databases, and Redis caching that connect them.</p><p>I also build LLM applications, RAG systems, and AI agents. I enjoy bringing the whole product together—from the first screen and data model to automation, deployment, and the details that make it reliable.</p></div><a className="text-link underline-link" href={profile.linkedin} target="_blank" rel="noopener noreferrer">A little more about me on LinkedIn <ArrowUpRight size={17}/></a></div></div></section>
      <Toolkit/>
      <section id="experience" className="section container experience-section" aria-labelledby="experience-title"><div className="experience-intro" data-reveal><div className="eyebrow">04 / THE JOURNEY</div><h2 id="experience-title">Learning by<br/><span className="serif">building.</span></h2><p className="section-lede">Where curiosity meets<br/>real-world experience.</p></div><div className="timeline"><article className="timeline-entry" data-reveal="slide"><div className="timeline-icon"><Workflow size={20}/></div><div className="timeline-meta"><span>DEC 2024 — PRESENT</span><span className="current-badge">Current</span></div><h3>Software Engineer — Applied AI</h3><span className="company-link">Bitontree</span><p>Building production AI across analytics, ecommerce, recruitment, and automation. Owning projects from requirement discovery and architecture to deployment and client delivery.</p><p>Working directly with stakeholders to connect LLMs, APIs, databases, and cloud services into reliable business workflows.</p></article><article className="timeline-entry education-entry" data-reveal="slide"><div className="timeline-icon"><GraduationCap size={21}/></div><div className="timeline-meta"><span>2021 — 2025</span></div><h3>B.Tech in Information Technology</h3><span className="company-link">Dharmsinh Desai University</span><p>Building the foundation. CPI: 8.04 / 10.</p></article></div></section>
      <section id="contact" className="contact-section" aria-labelledby="contact-title"><div className="container"><div className="eyebrow" data-reveal>05 / LET’S MAKE SOMETHING MATTER</div><div className="contact-main" data-reveal="wipe"><h2 id="contact-title">Your next idea.<br/><span className="serif">Our next conversation.</span></h2><a className="contact-arrow" href={`mailto:${profile.email}`} aria-label="Email Priyansh"><ArrowUpRight size={50} strokeWidth={1}/></a></div><div className="contact-bottom"><a className="email-link" href={`mailto:${profile.email}`}>{profile.email} <ArrowUpRight size={19}/></a><div className="social-links"><a href={profile.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin size={16}/> LinkedIn <ArrowUpRight size={14}/></a><a href="/Priyansh_Resume.pdf" download><Download size={16}/> Resume</a></div></div></div></section>
    </main><footer className="container site-footer"><a className="brand" href="#top" aria-label="Back to top">pd<span aria-hidden="true">✳</span></a><p>© {new Date().getFullYear()} Priyansh Dobariya</p><span>Built with intention. And a little AI.</span><a className="back-top" href="#top">Back to top <ArrowUp size={16}/></a></footer>
  </>;
}
