export const profile = { name: 'Priyansh Dobariya', role: 'Applied AI Engineer', email: 'priyansh20032003@gmail.com', linkedin: 'https://www.linkedin.com/in/priyansh203', description: 'Applied AI engineer building production LLM systems, RAG architectures, AI agents, and automation across analytics, ecommerce, and recruitment.' };

// Add future projects here. Include verified claims and approved public URLs only.
export const projects = [
  { id:'growstack', name:'Growstack AI', category:'CONVERSATIONAL ANALYTICS', title:'Big data. Simple conversations.', description:'Helping non-technical teams turn business questions into validated SQL queries and structured data exports.', technologies:['LangGraph','AWS Bedrock','ClickHouse','S3'], details:['Built natural-language-to-SQL workflows with schema-aware generation and query validation.','Designed routing and failure recovery for analytics workflows over ClickHouse datasets containing more than 330 million records.','Connected query results to structured data exports using S3.'] },
  { id:'urecruits', name:'uRecruits', category:'RECRUITMENT AUTOMATION', title:'More context. Better hiring workflows.', description:'Structured resume parsing, candidate matching, and decision support that keeps recruiters in the loop.', technologies:['Resume parsing','AI scoring','Human review'], details:['Developed workflows for resume parsing, candidate matching, and scoring.','Built structured evaluation pipelines that produce hiring insights for recruiter review.','Implemented monitoring, audit trails, human review workflows, and adverse-action support.'] },
  { id:'zyberon', name:'Zyberon AI', category:'ECOMMERCE & AUTOMATION', title:'From product to campaign.', description:'Connecting product data, generative AI, and marketing platforms into useful ecommerce workflows.', technologies:['Shopify','n8n','Meta APIs','Generative AI'], details:['Built automation workflows connecting Shopify, n8n, AI services, and marketing platforms.','Developed AI pipelines that analyze product context and generate advertising assets.','Connected product data, content generation, and campaign execution into automated workflows.'] },
  { id:'voice-agent', name:'AI Voice Agent', category:'VOICE & CONVERSATIONAL AI', title:'A conversation that moves things forward.', description:'Voice workflows for lead qualification, appointment scheduling, and contextual follow-ups.', technologies:['Retell AI','FastAPI','MongoDB'], details:['Built AI voice workflows for lead qualification and appointment scheduling.','Handled conversational context and follow-up workflows.','Implemented MongoDB-based state management with retry and recovery handling.'] },
];
export const skillGroups = [
  { title:'AI & intelligence', items:['LangGraph','LangChain','CrewAI','RAG','Agent orchestration','LLM evaluation','Embeddings','Hybrid search'] },
  { title:'The engineering', items:['Python','TypeScript','FastAPI','Next.js','Node.js','REST APIs','GraphQL','n8n'] },
  { title:'Data & infrastructure', items:['AWS','ClickHouse','PostgreSQL','MongoDB','Pinecone','Docker','S3','DynamoDB'] },
];
