export const demoStyles: Record<string, string> = {
  section: 'relative my-8 mb-20 overflow-hidden rounded-[28px] border border-[color:var(--line)] bg-[color:var(--surface)] p-5 shadow-[0_30px_90px_rgba(7,21,33,.06)] sm:p-8 lg:p-12',
  heading: 'flex flex-wrap items-center justify-between gap-6 [&>div]:min-w-0 [&>div]:flex-1 [&_h2]:my-2 [&_h2]:text-[clamp(30px,4.2vw,50px)] [&_h2]:leading-none [&_h2]:tracking-[-.045em] [&_p]:m-0 [&_p]:max-w-[650px] [&_p]:leading-relaxed [&_p]:text-[color:var(--muted)]',
  eyebrow: 'inline-flex items-center gap-2 text-[10px] font-bold tracking-[.18em] text-[color:var(--accent)] before:h-px before:w-5 before:bg-current', panel: 'mt-8 border-t border-[color:var(--line)] pt-7',
  macBrowser: 'min-w-0 overflow-hidden rounded-[19px] border border-[#263847] bg-[#f2f5f7] shadow-[0_34px_80px_rgba(7,21,33,.18),0_2px_4px_rgba(7,21,33,.1)]', macChrome: 'flex min-h-12 items-center gap-3 border-b border-[#2d3c49] bg-gradient-to-b from-[#1d2b37] to-[#14202a] px-4 py-2 text-[#c1cbd3]',
  macLights: 'flex shrink-0 gap-[7px] [&>span]:h-[10px] [&>span]:w-[10px] [&>span]:rounded-full [&>span]:bg-[#ff6059] [&>span:nth-child(2)]:bg-[#ffbd2e] [&>span:nth-child(3)]:bg-[#29c840]', macAddress: 'mx-auto min-w-0 max-w-[480px] flex-1 overflow-hidden text-ellipsis whitespace-nowrap rounded-md border border-[#41505d] bg-[#0c1720] px-4 py-1.5 text-center text-[11px] text-[#e5edf1] shadow-inner', macBadge: 'shrink-0 whitespace-nowrap text-[9px] font-extrabold tracking-[.1em] text-[#9aabb5] max-sm:hidden',
  macToolbar: 'flex min-h-[66px] flex-wrap items-center justify-between gap-3 border-b border-[#dfe5e9] bg-white px-[18px] py-3 text-[#17242d] [&_strong]:block [&_strong]:text-[13px]', notice: 'm-0 mt-[3px] text-[10px] leading-relaxed tracking-[.025em] text-[#75838d]', actions: 'mt-4 flex flex-wrap items-center gap-3',
  modeTabs: 'flex gap-1 overflow-auto rounded-[10px] border border-[#dfe5e9] bg-[#f3f6f8] p-[3px] [&>button]:min-h-[31px] [&>button]:whitespace-nowrap [&>button]:rounded-[7px] [&>button]:border-0 [&>button]:bg-transparent [&>button]:px-[10px] [&>button]:text-[11px] [&>button]:font-semibold [&>button]:text-[#687782] [&>button]:cursor-pointer [&>button[aria-selected=true]]:bg-[#17242d] [&>button[aria-selected=true]]:text-white', macContent: 'min-w-0',
  handsOn: 'min-h-0 bg-[#f3f6f8] bg-[radial-gradient(circle_at_100%_0,#e9eff4_0,transparent_34%)] p-[clamp(18px,2.6vw,30px)] text-[#17242d] [[data-project=growstack]_&]:bg-white [[data-project=growstack]_&]:p-0 [[data-project=mychatpdf]_&]:bg-white [[data-project=mychatpdf]_&]:p-0 [[data-project=zyberon]_&]:bg-white [[data-project=zyberon]_&]:p-0 [[data-project=urecruits]_&]:bg-white [[data-project=urecruits]_&]:p-0',
  grid: 'grid grid-cols-1 items-start gap-4 lg:grid-cols-[minmax(0,1.15fr)_minmax(320px,.85fr)]', two: 'grid grid-cols-1 gap-3 sm:grid-cols-2', card: 'min-w-0 rounded-2xl border border-[#dfe5e9] bg-white p-[clamp(20px,2.7vw,30px)] text-[#17242d] shadow-[0_8px_25px_rgba(21,38,51,.04)] [&>h3]:mb-1.5 [&>h3]:mt-0 [&>h3]:text-lg [&>p]:leading-relaxed [&>p]:text-[#52636e]',
  label: 'mb-[7px] mt-[18px] block text-[11px] font-bold tracking-[.02em] text-[#354751]', input: 'min-h-11 w-full min-w-0 rounded-[10px] border border-[#d8e0e5] bg-[#fbfcfd] px-3 py-[11px] text-[#17242d] shadow-inner outline-none hover:border-[#afbbc3] focus:border-[#5269ff] focus:ring-[3px] focus:ring-[#5269ff]/15', select: 'min-h-11 w-full min-w-0 rounded-[10px] border border-[#d8e0e5] bg-[#fbfcfd] px-3 py-[11px] text-[#17242d] shadow-inner outline-none hover:border-[#afbbc3] focus:border-[#5269ff] focus:ring-[3px] focus:ring-[#5269ff]/15', textarea: 'min-h-[100px] w-full min-w-0 resize-y rounded-[10px] border border-[#d8e0e5] bg-[#fbfcfd] px-3 py-[11px] text-[#17242d] shadow-inner outline-none focus:border-[#5269ff] focus:ring-[3px] focus:ring-[#5269ff]/15',
  button: 'min-h-[42px] cursor-pointer rounded-[10px] border border-[#d9e1e6] bg-white px-[15px] py-[10px] text-center text-xs font-semibold text-[#263842] shadow-sm transition hover:-translate-y-px hover:border-[#8f9da7] hover:shadow-md disabled:cursor-not-allowed disabled:opacity-50', primary: 'min-h-[42px] cursor-pointer rounded-[10px] border border-[#17242d] bg-[#17242d] px-[15px] py-[10px] text-center text-xs font-semibold text-white shadow-[0_7px_18px_rgba(16,31,41,.18)] transition hover:-translate-y-px hover:shadow-lg disabled:cursor-not-allowed disabled:opacity-50', choice: 'min-h-[42px] cursor-pointer rounded-[10px] border border-[#d9e1e6] bg-white px-[15px] py-[10px] text-xs font-semibold text-[#263842] shadow-sm transition data-[active=true]:border-[#5269ff] data-[active=true]:bg-[#edf0ff] data-[active=true]:text-[#243aa5]', choices: 'mb-4 flex flex-wrap items-center gap-3',
  hint: 'text-[13px] leading-relaxed text-[#74848e]', output: 'whitespace-pre-wrap break-words rounded-[11px] border border-[#dce3e7] bg-[#f7f9fb] p-4 font-mono text-xs leading-relaxed text-[#334650]', status: 'inline-block rounded-full bg-[#e7f7ed] px-[9px] py-[5px] text-xs font-bold text-[#227347]', divider: 'my-5 border-t border-[#e3e8eb]', metrics: 'grid grid-cols-2 gap-[10px] sm:grid-cols-3', metric: 'rounded-[11px] border border-[#e0e6e9] bg-[#f8fafb] p-[14px] text-[11px] text-[#60717c] [&>strong]:mt-1.5 [&>strong]:block [&>strong]:text-[21px] [&>strong]:text-[#17242d]', list: 'm-0 pl-5 [&>li]:py-[7px] [&>li]:leading-relaxed',
  timeline: 'relative mt-5 list-none p-0 [&>li]:ml-[5px] [&>li]:border-l-2 [&>li]:border-[#dfe5e9] [&>li]:px-[10px] [&>li]:py-3 [&>li]:pl-5 [&>li]:text-[#536570] [&>li[data-current=true]]:border-[#5269ff] [&>li[data-current=true]]:bg-[#5269ff]/5', graph: 'my-[18px] flex items-stretch gap-6 overflow-x-auto px-1 pb-5 pt-3 max-md:flex-col max-md:overflow-visible', node: 'relative min-h-[86px] w-[150px] shrink-0 cursor-pointer rounded-[10px] border border-[#d9e1e6] bg-[#f9fbfc] p-[13px] text-left text-xs font-semibold text-[#263842] shadow-sm data-[active=true]:border-[#5269ff] data-[active=true]:bg-[#edf0ff] max-md:w-full [&>span]:mt-[5px] [&>span]:block [&>span]:text-[11px] [&>span]:font-normal [&>span]:text-[#788892]', step: 'border-l-2 border-[#dfe5e9] py-3 pl-4 data-[active=true]:border-[#5269ff] data-[active=true]:bg-[#5269ff]/5', visualPreview: 'relative grid aspect-[4/3] place-items-center overflow-hidden rounded-xl border border-[#dce3e7] bg-[#edf1f4] shadow-inner [&>img]:h-full [&>img]:w-full [&>img]:object-cover', srOnly: 'sr-only'
};
